### ISSUE TITLE
Loads to log in screen but needs update

### ISSUE THREAD

**Issue by Markmiran** [GloriousEggroll/warframe-linux#25]
Hi, I can load it to the login stage, but once you login it tells me that a new version of warframe is out exit and rerun to update. I've done this at least 6 times with no luck. It doesn't bring up the update screen at all it just boots straight into the login menu. Any ideas?

**Comment by GloriousEggroll** [comment]
please try updating updater.sh, I edited it around 4 am this morning as another user was having the same problem. you dont need to reinstall, just download updater.sh from here and drop it into your warframe folder.

**Comment by Markmiran** [comment]
Thanks for getting back to me. I tried that and im still getting the same issue.  Warframe loads straight to the login screen, and i need to exit to update. I also double checked the dependencies.
Not sure what else to try.

**Comment by NeroBurner** [comment]
I did try to start the launcher.exe, but it loop-reboots itself

**Comment by GloriousEggroll** [comment]
if you guys could please try updater.sh with the changes i just committed

**Comment by bakethepizza** [comment]
Here is the message I get from running it with the updated updater.sh:

`
updater.sh: line 7: syntax error near unexpected token `newline'
updater.sh: line 7: `<!DOCTYPE html>'
`

**Comment by Markmiran** [comment]
Trying it out now, may take some time its redownloading the game.

**Comment by NeroBurner** [comment]
@bakethepizza you most probably did download the html page because on line 7 in the bash script there is only a comment https://github.com/GloriousEggroll/warframe-linux/blob/master/updater.sh#L7

the html of github starts at line 7 with `<!DOCTYPE html>`. Please download with the raw link https://raw.githubusercontent.com/GloriousEggroll/warframe-linux/master/updater.sh

**Comment by Markmiran** [comment]
Isn't this script supposed to just update warframe, not redownload the entire game? Because its redownloading my game, ive been waiting hours.  If ive done something wrong let me know.
Thanks guys..

**Comment by GloriousEggroll** [comment]
@Markmiran the problem with the script was that it was not logging or checking md5sums properly. the latest update to updater.sh should fix that. It's probably redownloading the files because it doesnt see the new md5sums in the list.

@bakethepizza as what nero said it looks like you downloaded the webpage instead of the actual updater.sh script. On github if you click to view updater.sh then click raw, then right click on the page and hit save as, it should save the actual script

**Comment by Markmiran** [comment]
No I re downloaded the zip and extracted the file from it. Not sure if he
was referring to me. Either way thanks, what you're saying explains why it
re downloaded.

**Comment by GloriousEggroll** [comment]
this should be resolved as of the latest script updates. closing
