### ISSUE TITLE
questions about updater.sh

### ISSUE THREAD

**Issue by NeroBurner** [GloriousEggroll/warframe-linux#27]
can you explain to me what this line does? I can't find an explanation through searching DuckDuckGo
https://github.com/GloriousEggroll/warframe-linux/blob/f1c346882fbaf28f35614056f265b662c93a6d78/updater.sh#L33
```
MD5SUM=${MD5SUM,,}
```

furthermore, I think we should download the files only if the local file has a different MD5sum than the file to download
https://github.com/GloriousEggroll/warframe-linux/blob/master/updater.sh#L64

**Comment by NeroBurner** [comment]
ah, found the answer to the first command: convert from uppercase to lowercase

**Comment by GloriousEggroll** [comment]
I'm still working out some of the kinks with the updater, and that was the idea behind updater.sh and what its supposed to be doing. it makes a list of all the current md5sums, then downloads the index and compares the index md5 sums to the current md5sum list, and is -supposed- to download the ones missing.

-technically- line 83 and 91 do the md5sum checking and updating automatically for 32 and 64 with the exception of the actual Warframe/.x64.exe itself, bit but theres no progress indication on them, which is why i wanted to do it by hand first so that i could get rid of those lines later on.

to make this stupid easy I could just make it check the md5sum of only warframe.exe and warframe.x64.exe and redownload them if needed, then update the rest via lines 83 and 91 but again, no progress shown that way

**Comment by NeroBurner** [comment]
the current progress does not take filesize in account. index.txt has the last column as a sort of filesize. I don't know how, but we could incorporate those into the progess. Maybe we could first generate a list of files we need to download and then do the downloads. With this we know how much we need to download and what percentage each file has

**Comment by NeroBurner** [comment]
another question: why is most of `wf.reg` gone? don't we need those entries anymore?

**Comment by GloriousEggroll** [comment]
the wf.reg entries that were removed only pertain to warframe's official launcher.
